import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// const sidebars: SidebarsConfig = {
//   tutorialSidebar: [{ type: "autogenerated", dirName: "." }],
// };

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    'intro',
    // 他の表示したいドキュメントを手動で指定
    // 'REST API'フォルダを含めない
  ],
};

export default sidebars;
