components:
  schemas:
    Body_upload_file_api_upload_post:
      properties:
        file:
          format: binary
          title: File
          type: string
      required:
        - file
      title: Body_upload_file_api_upload_post
      type: object
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: "#/components/schemas/ValidationError"
          title: Detail
          type: array
      title: HTTPValidationError
      type: object
    UploadResponse:
      properties:
        id:
          title: Id
          type: string
        message:
          title: Message
          type: string
      required:
        - message
        - id
      title: UploadResponse
      type: object
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
              - type: string
              - type: integer
          title: Location
          type: array
        msg:
          title: Message
          type: string
        type:
          title: Error Type
          type: string
      required:
        - loc
        - msg
        - type
      title: ValidationError
      type: object
info:
  title: FastAPI
  version: 0.1.0
openapi: 3.1.0
paths:
  /:
    get:
      operationId: read_root__get
      responses:
        "200":
          content:
            application/json:
              schema: {}
          description: Successful Response
      summary: Read Root
  /api/repositories/{repo_id}:
    delete:
      operationId: delete_repository_api_repositories__repo_id__delete
      parameters:
        - in: path
          name: repo_id
          required: true
          schema:
            title: Repo Id
            type: string
      responses:
        "204":
          description: Successful Response
        "400":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HTTPValidationError"
          description: Validation Error
      summary: Delete Repository
      tags:
        - repositories
  /api/upload:
    post:
      operationId: upload_file_api_upload_post
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: "#/components/schemas/Body_upload_file_api_upload_post"
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UploadResponse"
          description: Successful Response
        "400":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HTTPValidationError"
          description: Validation Error
      summary: Upload File
      tags:
        - upload
